pdf:
	pdflatex Supervised_Machine_Learning_Methods.tex

pdf_follow_changes:
	latexmk -pdf -pdflatex -pvc Supervised_Machine_Learning_Methods.tex

check:
	lacheck Supervised_Machine_Learning_Methods.tex

clean:
	rm -f *.aux  *.log .nav *.out *.snm *.toc *.nav *.fdb_latexmk *.fls *.xdv
